Tziminadis/card revamping
felipprodrigues/adote-animal pull request #14
Opened 2021-04-15 00:38 UTC by Tziminadis

2021-04-15 00:42 UTC, Tziminadis commented
I tried out an ideia in the lower button of the card and would like to know what you think about it. Couldn't get it to follow the "body__card" element radius, though.

2021-04-18 23:34 UTC, felipprodrigues commented
Overall your PR looks good but there were some major changes on the design and would be pleased if you could follow it. Not sure this is the final one but I think "design wise" we are getting there

2021-04-18 23:38 UTC, felipprodrigues requested changes

2021-04-18 23:38 UTC, felipprodrigues commented on _src/css/_body.scss
>    &__frame::after{
We no longer will be using this pseudo class

2021-04-27 21:59 UTC, felipprodrigues requested changes

2021-04-27 21:59 UTC, felipprodrigues commented on _src/css/_body.scss
> +    bottom: 15px;
This rule shouldn't be here. It is pushing the entire component out of its parent

2021-04-27 21:59 UTC, felipprodrigues commented on _src/css/_body.scss
> +    margin-top: 35px;
There's no need for the margin to be this much. We can use the default marging of this element to set the correct spacing between the title and text.

2021-04-27 21:59 UTC, felipprodrigues commented on _src/body/_body.jade
>    .body__card
We can size 50px down the body__card element. It should fit better the entire content held in it.

2021-05-01 19:04 UTC, felipprodrigues approved these changes

2021-05-01 19:04 UTC, merged